"""Exception classes for strapi-kit."""

from .errors import (
    AuthenticationError,
    AuthorizationError,
    ConfigurationError,
    ConflictError,
    ConnectionError,
    FormatError,
    ImportExportError,
    MediaError,
    MethodNotAllowedError,
    NetworkError,
    NotFoundError,
    RateLimitError,
    RelationError,
    ServerError,
    StrapiError,
    TimeoutError,
    UnstructuredResponseError,
    ValidationError,
)

__all__ = [
    "StrapiError",
    "ConfigurationError",
    "AuthenticationError",
    "AuthorizationError",
    "NotFoundError",
    "ValidationError",
    "ConflictError",
    "MethodNotAllowedError",
    "UnstructuredResponseError",
    "NetworkError",
    "ConnectionError",
    "TimeoutError",
    "RateLimitError",
    "ServerError",
    "ImportExportError",
    "FormatError",
    "RelationError",
    "MediaError",
]
